export const codeExamples: { [key: string]: string[] } = {
  TypeScript: [
    'import { app } from "@helio/edge";',
    "",
    'app.get("/hello", (c) => {',
    "  return c.json({",
    '    message: "Hello, world.",',
    "    region: c.region,",
    "  });",
    "});",
    "",
    "export default app;",
  ],
  Python: [
    "from helio import App",
    "",
    "app = App()",
    "",
    '@app.route("/hello")',
    "def hello(request):",
    "    return {",
    '        "message": "Hello, world.",',
    '        "region": request.region',
    "    }",
  ],
  Go: [
    "package main",
    "",
    'import "helio.dev/edge"',
    "",
    "func main() {",
    "  app := edge.New()",
    '  app.Get("/hello", func(c edge.Context) {',
    '    c.JSON(200, "Hello, world.")',
    "  })",
    "}",
  ],
};
