import type { Visit } from "./data";
export const visits: Visit[] = [
  {
    id: 1,
    patient: "Emma Wilson",
    age: 34,
    initials: "EW",
    purpose: "Annual wellness visit",
    doctor: "allen",
    time: 540,
    duration: 60,
    day: 3,
    tone: "peach",
    status: "Checked in",
    note: "Review sleep, movement and the annual wellness plan. Emma would like to discuss her return to running.",
  },
  {
    id: 2,
    patient: "Noah Williams",
    age: 28,
    initials: "NW",
    purpose: "Follow-up consultation",
    doctor: "chen",
    time: 495,
    duration: 45,
    day: 3,
    tone: "mint",
    status: "Ready",
    note: "Follow-up after the previous consultation. Review the home monitoring notes and agree the next check-in.",
  },
  {
    id: 3,
    patient: "Sophie Davis",
    age: 42,
    initials: "SD",
    purpose: "Routine screening",
    doctor: "reed",
    time: 525,
    duration: 45,
    day: 3,
    tone: "lilac",
    status: "Confirmed",
    note: "Routine screening and preventive care conversation. Previous records are available in the patient history.",
  },
  {
    id: 4,
    patient: "James Miller",
    age: 56,
    initials: "JM",
    purpose: "Care plan review",
    doctor: "allen",
    time: 660,
    duration: 75,
    day: 3,
    tone: "mint",
    status: "Confirmed",
    note: "Review the current care plan and medication list. Bring the latest laboratory summary into the conversation.",
  },
  {
    id: 5,
    patient: "Lily Thompson",
    age: 24,
    initials: "LT",
    purpose: "First consultation",
    doctor: "chen",
    time: 630,
    duration: 60,
    day: 3,
    tone: "peach",
    status: "New patient",
    note: "First visit. Begin with the patient's priorities, then review relevant health history and next steps.",
  },
  {
    id: 6,
    patient: "Grace Walker",
    age: 39,
    initials: "GW",
    purpose: "Follow-up consultation",
    doctor: "reed",
    time: 690,
    duration: 45,
    day: 3,
    tone: "peach",
    status: "Confirmed",
    note: "Discuss progress and any new questions since the last consultation.",
  },
  {
    id: 7,
    patient: "Henry Taylor",
    age: 61,
    initials: "HT",
    purpose: "Routine check-in",
    doctor: "allen",
    time: 840,
    duration: 45,
    day: 3,
    tone: "lilac",
    status: "Confirmed",
    note: "Routine check-in and review of daily activity. Confirm the next appointment before leaving.",
  },
  {
    id: 8,
    patient: "Ava Brown",
    age: 31,
    initials: "AB",
    purpose: "Annual wellness visit",
    doctor: "reed",
    time: 825,
    duration: 60,
    day: 3,
    tone: "mint",
    status: "Confirmed",
    note: "Annual wellness review and preventive care planning.",
  },
  {
    id: 9,
    patient: "Daniel Lee",
    age: 45,
    initials: "DL",
    purpose: "Care plan review",
    doctor: "allen",
    time: 570,
    duration: 60,
    day: 2,
    tone: "mint",
    status: "Complete",
    note: "Care plan reviewed. Follow-up scheduled in six weeks.",
  },
  {
    id: 10,
    patient: "Isla Martin",
    age: 30,
    initials: "IM",
    purpose: "First consultation",
    doctor: "chen",
    time: 600,
    duration: 60,
    day: 4,
    tone: "peach",
    status: "Confirmed",
    note: "First consultation and patient history.",
  },
  {
    id: 11,
    patient: "Theo Clark",
    age: 38,
    initials: "TC",
    purpose: "Routine check-in",
    doctor: "reed",
    time: 555,
    duration: 45,
    day: 1,
    tone: "lilac",
    status: "Complete",
    note: "Routine check-in completed.",
  },
  {
    id: 12,
    patient: "Mia Adams",
    age: 27,
    initials: "MA",
    purpose: "Annual wellness visit",
    doctor: "allen",
    time: 510,
    duration: 60,
    day: 0,
    tone: "peach",
    status: "Complete",
    note: "Annual wellness plan agreed.",
  },
];
