import {ArrowLeft,ArrowUpRight,Download} from 'lucide-react';
import type {Brand} from '../shared/types';
import {BrandLogo} from '../shared/BrandLogo';
import {projectUrl} from '../projects';
import './brand-kit.css';
function LogoSpecimen({brand,invert=false}:{brand:Brand;invert?:boolean}){return <div className="kit-specimen" style={{background:brand.colors[invert?0:1]?.hex,color:brand.colors[invert?1:0]?.hex,fontFamily:brand.fonts.heading}}><BrandLogo brand={brand}/><span>{invert?'Reverse lockup':'Primary lockup'}</span></div>}
export function BrandKit({brand}:{brand:Brand}){
 const base=`${import.meta.env.BASE_URL}brand-kits/${brand.slug}/`;
 return <div className="brand-kit" style={{'--kit-ink':brand.colors[0].hex,'--kit-accent':brand.colors[2]?.hex,'--kit-display':`'${brand.fonts.heading}'`,'--kit-body':`'${brand.fonts.body}'`} as React.CSSProperties}><header className="kit-header"><a href={import.meta.env.BASE_URL}><ArrowLeft size={17}/> Collection</a><a href={projectUrl(brand.slug)}>View website <ArrowUpRight size={16}/></a></header><main><section className="kit-intro"><span>{brand.category}</span><h1>{brand.name}</h1><p>{brand.tagline}</p></section><section className="kit-story"><h2>A brand with a purpose.</h2><p>{brand.description}</p></section><section className="kit-section"><div className="kit-section-heading"><h2>The identity</h2><p>{brand.logoMeaning}</p></div><div className="kit-logo-grid"><LogoSpecimen brand={brand}/><LogoSpecimen brand={brand} invert/></div><div className="kit-symbol-row"><div style={{color:brand.colors[0].hex}}><BrandLogo brand={brand} symbolOnly/><span>Symbol</span></div><div className="kit-icon" style={{background:brand.colors[0].hex,color:brand.colors[1]?.hex}}><BrandLogo brand={brand} symbolOnly/></div><p>Keep clear space equal to one quarter of the symbol height. Use the single-color mark on busy backgrounds.</p></div></section><section className="kit-section"><div className="kit-section-heading"><h2>Color system</h2><p>A deliberate palette for the product and its communications.</p></div><div className="kit-colors">{brand.colors.map(color=><div key={color.hex}><div style={{background:color.hex}}/><h3>{color.name}</h3><code>{color.hex.toUpperCase()}</code></div>)}</div></section><section className="kit-section"><div className="kit-section-heading"><h2>Typography</h2><p>{brand.artDirection}</p></div><div className="kit-type-grid"><div><span>Display / {brand.fonts.heading}</span><p style={{fontFamily:brand.fonts.heading}}>Aa Bb Cc<br/>Design with purpose.</p></div><div><span>Body / {brand.fonts.body}</span><p style={{fontFamily:brand.fonts.body}}>A clear voice. A considered experience.</p><div style={{fontFamily:brand.fonts.body}}>ABCDEFGHIJKLMNOPQRSTUVWXYZ<br/>abcdefghijklmnopqrstuvwxyz<br/>0123456789</div></div></div></section><section className="kit-download"><div><h2>Make it yours.</h2><p>Vector logos, color tokens, typography guidance, and a visual brand sheet.</p></div><div><a href={`${base}brand-kit.pdf`} download><Download size={17}/> Brand sheet PDF</a><a href={`${base}logo-package.zip`} download><Download size={17}/> Logo package</a></div></section></main><footer className="kit-footer"><BrandLogo brand={brand}/><a href={projectUrl(brand.slug)}>Explore {brand.name} <ArrowUpRight size={16}/></a></footer></div>
}
