import {useState} from 'react';
import {ArrowUpRight,Search,X} from 'lucide-react';
import {projects,projectUrl} from '../projects';
import {BrandLogo} from '../shared/BrandLogo';
import type {Brand} from '../shared/types';
import './gallery.css';
const groups=['All projects','Landing pages','Dashboards','Shops','Editorial'];
function groupFor(brand:Brand){const text=`${brand.category} ${brand.purpose}`.toLowerCase();return /dashboard|workspace|logistics platform|music platform/.test(text)?'Dashboards':/ecommerce|store|shop|ceramic|skincare|jewel/.test(text)?'Shops':/magazine|journal|editorial/.test(text)?'Editorial':'Landing pages'}
function ProjectCard({brand,index}:{brand:Brand;index:number}){
 const [hasPreview,setHasPreview]=useState(true);
 return <article className="collection-card"><a className="collection-preview" href={projectUrl(brand.slug)} aria-label={`Explore ${brand.name}`} style={{background:brand.colors[1]?.hex,color:brand.colors[0].hex}}>{hasPreview?<img src={`${import.meta.env.BASE_URL}previews/${brand.slug}.jpg`} alt={`${brand.name} website preview`} loading="lazy" onError={()=>setHasPreview(false)}/>:<div className="collection-placeholder" style={{fontFamily:brand.fonts.heading}}><BrandLogo brand={brand}/><p>{brand.tagline}</p></div>}<span className="collection-view">Explore project <ArrowUpRight size={16}/></span></a><div className="collection-card-meta"><div><a href={projectUrl(brand.slug)} className="collection-project-title">{brand.name}</a><p>{brand.category}</p></div><span>{String(index+1).padStart(2,'0')}</span></div><div className="collection-card-links"><span>{brand.tagline}</span><a href={`${projectUrl(brand.slug)}brand/`}>Brand kit <ArrowUpRight size={13}/></a></div></article>
}
export function Gallery(){
 const [group,setGroup]=useState('All projects');const [query,setQuery]=useState('');
 const filtered=projects.filter(({brand})=>(group==='All projects'||groupFor(brand)===group)&&`${brand.name} ${brand.category} ${brand.tagline}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="collection"><header className="collection-header"><a href={import.meta.env.BASE_URL} className="collection-wordmark"><span className="collection-mark" aria-hidden="true">✳</span> Twenty Web Studies</a><nav aria-label="Collection navigation"><a href="#projects">The collection</a><a href="https://github.com/pablomanjarres/twenty-web-studies" target="_blank" rel="noreferrer">Source code <ArrowUpRight size={15}/></a></nav></header><main><section className="collection-intro"><div><p className="collection-kicker">Independent identities, considered interfaces.</p><h1>Twenty different<br/>ways to see the web.</h1></div><div className="collection-intro-note"><span>20</span><p>From a quiet alpine retreat to a bustling product workspace. Twenty complete visual worlds, each with a purpose and a personality of its own.</p><a href="#projects">Find your perspective <ArrowUpRight size={18}/></a></div></section><section id="projects" className="collection-projects"><div className="collection-tools"><div className="collection-filters" role="group" aria-label="Filter projects">{groups.map(item=><button key={item} className={group===item?'is-active':''} aria-pressed={group===item} onClick={()=>setGroup(item)}>{item}</button>)}</div><label className="collection-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a project" aria-label="Find a project"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={14}/></button>}</label></div><div className="collection-grid">{filtered.map(({brand})=><ProjectCard key={brand.slug} brand={brand} index={projects.findIndex(p=>p.brand.slug===brand.slug)}/>)}</div>{!filtered.length&&<p className="collection-empty">No projects match. Try another name or view all projects.</p>}</section></main><footer className="collection-footer"><span>Twenty Web Studies</span><p>Distinct brands. Different perspectives.</p><a href="#top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Back to top <ArrowUpRight size={16}/></a></footer></div>
}
