export const asset = (id: number) =>
  `${import.meta.env.BASE_URL}images/orbit/avatar-${id}.jpg`;
export const projects = [
  {
    name: "Brand refresh",
    client: "Luma Studio",
    category: "Design",
    progress: 72,
    tasks: "18 / 25 tasks",
    date: "Oct 18",
    color: "#e8dff8",
    ink: "#8563b5",
    icon: "✳",
    team: [1, 2, 3],
  },
  {
    name: "Website launch",
    client: "Maison & Co.",
    category: "Development",
    progress: 48,
    tasks: "12 / 25 tasks",
    date: "Oct 24",
    color: "#f9e5dc",
    ink: "#bd876b",
    icon: "↗",
    team: [2, 3],
  },
  {
    name: "Autumn campaign",
    client: "The Good Life",
    category: "Marketing",
    progress: 86,
    tasks: "24 / 28 tasks",
    date: "Oct 12",
    color: "#deeee7",
    ink: "#719a8a",
    icon: "◒",
    team: [1, 3],
  },
];
export const initialTasks = [
  {
    id: 1,
    name: "Finalize homepage concepts",
    project: "Website launch",
    date: "Today",
    priority: "High",
    done: false,
  },
  {
    id: 2,
    name: "Review visual identity guidelines",
    project: "Brand refresh",
    date: "Today",
    priority: "Medium",
    done: false,
  },
  {
    id: 3,
    name: "Prepare campaign presentation",
    project: "Autumn campaign",
    date: "Tomorrow",
    priority: "High",
    done: false,
  },
  {
    id: 4,
    name: "Share moodboard with the team",
    project: "Brand refresh",
    date: "Oct 10",
    priority: "Low",
    done: true,
  },
];
