import type { Task } from "./data";

export const initialTasks: Task[] = [
  {
    id: 1,
    title: "Make the first impression count",
    kind: "Design",
    status: "In progress",
    owner: "Sam Rivera",
    avatar: 1,
    due: "Thu, 8 Oct",
    start: 1,
    days: 3,
    hours: 12,
    description:
      "Explore a quieter opening for the Maison storefront. Lead with the object, then make the collection easy to enter.",
    checks: [
      "Gather material references",
      "Build two opening concepts",
      "Share with the studio",
    ],
    checked: [0],
    note: "Keep the opening useful at every screen size.",
  },
  {
    id: 2,
    title: "A little less, a little better",
    kind: "Research",
    status: "Done",
    owner: "Alex Chen",
    avatar: 2,
    due: "Tue, 6 Oct",
    start: 0,
    days: 2,
    hours: 8,
    description:
      "Bring the customer research into a clear collection story, with fewer choices and more useful detail.",
    checks: ["Six customer conversations", "Share the synthesis"],
    checked: [0, 1],
    note: "Care information is an important part of the buying decision.",
  },
  {
    id: 3,
    title: "A collection with a point of view",
    kind: "Content",
    status: "Review",
    owner: "Jules Park",
    avatar: 3,
    due: "Fri, 9 Oct",
    start: 2,
    days: 3,
    hours: 10,
    description:
      "Organize the collection around how pieces feel in a room, with the material and care details close at hand.",
    checks: [
      "Draft the collection story",
      "Pair images and captions",
      "Check the reading order",
    ],
    checked: [0, 1],
    note: "Review the short captions together on Friday.",
  },
  {
    id: 4,
    title: "How it feels in your hands",
    kind: "Design",
    status: "To do",
    owner: "Alex Chen",
    avatar: 2,
    due: "Fri, 9 Oct",
    start: 3,
    days: 2,
    hours: 6,
    description:
      "Build a product detail flow with finish choices, dimensions, and an obvious next step.",
    checks: ["Finish selector", "Dimension view", "Mobile detail"],
    checked: [],
    note: "",
  },
  {
    id: 5,
    title: "One last look together",
    kind: "Review",
    status: "To do",
    owner: "Sam Rivera",
    avatar: 1,
    due: "Fri, 9 Oct",
    start: 4,
    days: 1,
    hours: 2,
    description:
      "A studio review of the flow, decisions, and details before the collection presentation.",
    checks: ["Read the journey aloud", "Check the interactive states"],
    checked: [],
    note: "Bring the research synthesis and both opening concepts.",
  },
  {
    id: 6,
    title: "Material & care library",
    kind: "Content",
    status: "Done",
    owner: "Jules Park",
    avatar: 3,
    due: "Tue, 6 Oct",
    start: 0,
    days: 2,
    hours: 5,
    description:
      "Give every object a clear material specification and a short care note.",
    checks: ["Verify dimensions", "Edit care instructions"],
    checked: [0, 1],
    note: "Keep the language direct and practical.",
  },
];
